name: lives
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_icons:
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/